### PR TITLE
BASIC-1435: added displays: directory, profiles, list

### PR DESCRIPTION
**Pull request by cjwest**

### CODE REVIEW

**Comment by sherakama** [comment]
A few things are missing from this...

# Please submit a pull request to the JSA/JS+ install profile that adds a well class to the new exposed filter block.
# The sidebar blocks are in the wrong order. The exposed filter block is above the links.
# The menu links on the installation profiles should be updated to reflect the new URLs
# The original views should be disabled.

**Comment by sherakama** [comment]
@cjwest,

Is this still a valid pull request?

**Comment by cjwest** [comment]
Ahh, umm, let's make these changes in their own views.

**Comment by cjwest** [comment]
[cid:52fa1e13-22a0-423f-830d-4ef2006a41eb]


________________________________

**Pull request closed without merging**
