### PR TITLE
Grid view

### PR DESCRIPTION
**Pull request by cjwest**
Hey Shea,

I need a grid view for the related content feature. 
Here's a pic:
https://asset1.basecamp.com/2577217/projects/5303798/attachments/113157168/b9dc31f8d7c16f47e26b0480cf97ec8b0010/original/Research%20Area%20page%20mockup.png

I'm not getting the CSS to work. It is supposed to remove the line above the first item. It works in css-injector, but not in the file. Will you please look at it?

Anyhow, I'm moving on to use it in the related content.
I'd love your feedback.

Cheers,
Caryl

### CODE REVIEW

**Comment by sherakama** [comment]
@cjwest, the link to the image in your comment gives me a 403 denied response. Could you just upload it here Thanks.

**Comment by sherakama** [comment]
Depends on #36

**Comment by cjwest** [comment]
Fooey! I was hoping that I had separated the to requests.  Where's the dependency?



________________________________

**Comment by sherakama** [comment]
The first 4 commits of this are from BASIC-1435

**Comment by cjwest** [comment]
If I rebuild this, should I start from 7.x-5.x-dev?



________________________________

**Comment by sherakama** [comment]
That is the usual recommended approach unless you need the code in the other feature branch.

You can start a new branch off of 5.x and cherry pick the one commit you want from the existing work instead of throwing it away. 

If you don�t want to start a new branch you can resolve pull #36 first.

-Shea

**Comment by cjwest** [comment]
Not to make this any more complicated, but I need this view on soe-jsa.


the Stanford Person on SoE-JSA is 7.x-3.0-alpha8.


What do you recommend?



________________________________

**Comment by sherakama** [comment]
Is it just for one site?

If it is then just make it on that site and be done with it. If it needs to come back into the product you will have to have a 3.x version and a 5.x version. I would start from the 3.x branch and then see if you can cherry pick the code into the 5.x version.

-Shea

**Comment by cjwest** [comment]
This is for all the SoE department sites.




________________________________

**Comment by sherakama** [comment]
If it is just for SOE then my question is �Does this belong in the main feature?� If it does not create a fork of this project and get cracking on the SOE specific stuff.

-Shea

**Comment by cjwest** [comment]
Yeah, okay. What repo should I use for this new SoE specific grid view?

________________________________

**Comment by sherakama** [comment]
I think SOE needs their own GitHub account for housing their forks of our products. There is an SU-SOE account already. I would get access to it and add me if you can as well.

https://github.com/SU-SOE

-Shea

**Pull request closed without merging**
