### PR TITLE
Basic 2008

### PR DESCRIPTION
**Pull request by cjwest**
Okay, @sherakama, I removed the rewrite with the h2.

### CODE REVIEW

**Comment by cjwest** [comment]
Oh, I've also included some description updates.

**Comment by sherakama** [comment]
The double heading issue is in every view that uses grouping. Can you also do this for faculty, staff, list grouped, etc.

Thank you.

**Comment by cjwest** [comment]
Okay @sherakama, I think I removed all the h2 rewrites. 😄

**Comment by sherakama** [comment]
Woot. That looks like it. Nice work and thank you.

**Comment by tsui1** [comment]
:clap:

**Pull request merged**
