### PR TITLE
CAP-52 Map 4 more fields from cap API

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added 3 fields and map 4 fields to the API
- see https://github.com/SU-SWS/stanford_profile/pull/294

# Need Review By (Date)
- 9/21

# Urgency
- low

# Steps to Test
- see https://github.com/SU-SWS/stanford_profile/pull/294

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Missing entity form and entity view displays.

**Comment by pookmish** [comment]
The fields are just hidden in the form and the display. its not really necessary to update the form or view displays.

**Comment by sherakama** [comment]
I think I'd rather be explicit than to rely on the defaults.

**Comment by pookmish** [comment]
Form and view configs now have the fields hidden.

**Pull request merged**
